### ISSUE TITLE
Issues getting server to start on Mac locally

### ISSUE THREAD

**Issue by enkota** [renoki-co/clusteer#3]
Hey,

Thanks for updating. I'm having some issues trying to get the `php artisan clusteer:serve` to start. I have installed the chrome binary and linked it directly to the correct path. Checked perms and also able to run the binary fine outside clusteer.

After starting, I eventually get:
`Clusteer Server failed with exit code 0% .`

I've also tested changing the port to 9515 which is what the binary loads externally, but no joy. 

If I run `php artisan clusteer:serve --debug` it seems to stay up, but not getting any return with:

Exception when trying to get a screenshot:

`file_get_contents(http://localhost:9515?until_idle=1&amp;screenshot=1&amp;quality=75&amp;url=https%3A%2F%2Flaravel.com): failed to open stream: HTTP request failed!`

Am I missing something?

Cheers!

**Comment by rennokki** [comment]
The exit codes are not really verbose at this level, and it's a good idea for me to make them work well. You can however debug the process by getting the command that's ran using:

```
php artisan clusteer:serve --show
```

You can then copy the entire string that's been output and run it individually and see what's going on.

**Comment by enkota** [comment]
Hey @rennokki thanks for the reply. Upon running that command it returns:

```
UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r809590 is guaranteed to work.
    at Cluster.<anonymous> (.../node_modules/puppeteer-cluster/dist/Cluster.js:119:23)rogress:  0 / 0 (100.00%), errors: 0 (0.00%)
    at Generator.throw (<anonymous>)nd)
    at rejected (.../node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
(node:88040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:88040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Potentially looks like an issue with my Chrome version. Will see what I can do there!

Thanks!

**Comment by rennokki** [comment]
You can pass multiple start-up variables when running `clusteer:serve`. Just run `php artisan clusteer:serve --help` to see the rest of the flags you can pass, like the path to the chromium binary you'd like to use.

I'll update puppeteer to ^5.4.1 and see how the tests behave.

**Comment by rennokki** [comment]
I have also updated the docs to match the testing package.json versions: https://github.com/renoki-co/clusteer/commit/fc8ca9afd61677c5a0fdb2e681b88979f63f01e9
