### ISSUE TITLE
Clusteer server failed with exit code 0

### ISSUE THREAD

**Issue by imsus** [renoki-co/clusteer#4]
Running `php artisan clusteer:serve` always failed with exit code 0.

This is the output of `php artisan clusteer:serve --show`

```sh
PORT="'8080'" MAX_BROWSERS="'1'" CHROMIUM_PATH="'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'" $(which node) vendor/renoki-co/clusteer/server.js
```

and actually why there is always a single-quotation mark wrapping arguments?
```sh
PORT="'8080'"
```

The culprit is in https://github.com/renoki-co/clusteer/blob/3ee1a94870599962065ff9a6b7802e4c26dc19fe/src/ClusteerServer.php#L173

If i comment it out it here is the result
```sh
PORT="8080" MAX_BROWSERS="1" CHROMIUM_PATH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" $(which node) vendor/renoki-co/clusteer/server.js
```

And it work normally.

**Comment by rennokki** [comment]
Thanks for noticing this bug, I have fixed it in https://github.com/renoki-co/clusteer/commit/4e3a943db2aaf65177c0802341e0e9f506d6a26b by removing the double quotes on each pairing. That should fix it.
